### PR TITLE
Bl sidebar

### PR DESCRIPTION
**Pull request by belv2c**

### CODE REVIEW

**Comment by DreRandaci** [comment]
for what the color scheme is, it looks great. awesome job 🥇

**Comment by DreRandaci** [comment]
although, for the requirements, we may need to make the grid fill in the main area more (the 30%/70% ratio). after this merges we can easily mess with that @harringtonben @RobertShock

**Comment by harringtonben** [comment]
dem colors though 👍

**Comment by belv2c** [comment]
Oh yeah, totally forgot about that. I must have been distracted by the 🙌🏻amazing colors. Easy fix!

**Pull request merged**
